const resList = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "731707",
        name: "Creams and berrys",
        uuid: "1deaba58-3e40-4b79-ac25-2f03bb96f756",
        city: "1",
        ar: 3.8,
        area: "Ramamurthy nagar",
        totalRatingsString: "",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        cuisines: ["Bakery"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "creams-and-berrys-ramamurthy-nagar-ramamurthy-nagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Sbi Bank Colony",
        parentId: 434554,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 9800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9800,
          message: "",
          title: "Delivery Charge",
          amount: "9800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7387083~p=1~eid=00000189-7432-0d7e-22dc-875200d9014f~srvts=1689871584638~89290",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 0,
          lastMileDistance: 9.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },

  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "731709",
        name: "prince da dhaba",
        uuid: "1deaba58-3e40-4b79-ac25-2f03bb96f756",
        city: "1",
        ar: 4.2,
        area: "Ramamurthy nagar",
        totalRatingsString: "",
        cloudinaryImageId: "a30ed459ccdc89cf1f3ab91def783582",
        cuisines: ["Bakery"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "creams-and-berrys-ramamurthy-nagar-ramamurthy-nagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Sbi Bank Colony",
        parentId: 434554,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 9800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9800,
          message: "",
          title: "Delivery Charge",
          amount: "9800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7387083~p=1~eid=00000189-7432-0d7e-22dc-875200d9014f~srvts=1689871584638~89290",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 0,
          lastMileDistance: 9.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "731708",
        name: "prince da dhaba",
        uuid: "1deaba58-3e40-4b79-ac25-2f03bb96f756",
        city: "1",
        ar: 4.8,
        area: "Ramamurthy nagar",
        totalRatingsString: "",
        cloudinaryImageId:
          "v1675667626/PC_Creative%20refresh/South_Indian_4.png",
        cuisines: ["Bakery"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "creams-and-berrys-ramamurthy-nagar-ramamurthy-nagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Sbi Bank Colony",
        parentId: 434554,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 9800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9800,
          message: "",
          title: "Delivery Charge",
          amount: "9800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7387083~p=1~eid=00000189-7432-0d7e-22dc-875200d9014f~srvts=1689871584638~89290",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 0,
          lastMileDistance: 9.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },

  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "731701",
        name: "prince da dhaba",
        uuid: "1deaba58-3e40-4b79-ac25-2f03bb96f756",
        city: "1",
        ar: 3.6,
        area: "Ramamurthy nagar",
        totalRatingsString: "",
        cloudinaryImageId:
          "v1674029846/PC_Creative%20refresh/3D_bau/banners_new/Idli.png",
        cuisines: ["Bakery"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "creams-and-berrys-ramamurthy-nagar-ramamurthy-nagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Sbi Bank Colony",
        parentId: 434554,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 9800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9800,
          message: "",
          title: "Delivery Charge",
          amount: "9800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7387083~p=1~eid=00000189-7432-0d7e-22dc-875200d9014f~srvts=1689871584638~89290",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 0,
          lastMileDistance: 9.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },

  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "731703",
        name: "prince da dhaba",
        uuid: "1deaba58-3e40-4b79-ac25-2f03bb96f756",
        city: "1",
        ar: 4.0,
        area: "Ramamurthy nagar",
        totalRatingsString: "",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        cuisines: ["Bakery"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "creams-and-berrys-ramamurthy-nagar-ramamurthy-nagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Sbi Bank Colony",
        parentId: 434554,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 9800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9800,
          message: "",
          title: "Delivery Charge",
          amount: "9800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7387083~p=1~eid=00000189-7432-0d7e-22dc-875200d9014f~srvts=1689871584638~89290",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 0,
          lastMileDistance: 9.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },

  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "731705",
        name: "prince da dhaba",
        uuid: "1deaba58-3e40-4b79-ac25-2f03bb96f756",
        city: "1",
        ar: 4.1,
        area: "Ramamurthy nagar",
        totalRatingsString: "",
        cloudinaryImageId:
          "v1674029858/PC_Creative%20refresh/3D_bau/banners_new/Pure_Veg.png",
        cuisines: ["Bakery"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "creams-and-berrys-ramamurthy-nagar-ramamurthy-nagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Sbi Bank Colony",
        parentId: 434554,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 9800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9800,
          message: "",
          title: "Delivery Charge",
          amount: "9800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7387083~p=1~eid=00000189-7432-0d7e-22dc-875200d9014f~srvts=1689871584638~89290",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 0,
          lastMileDistance: 9.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];
export default resList;
